train_dataset: 
  name: modelnet
  args:
    root_dir: modelnet40_manually_aligned
    class_map: modelnet11
    split: train
  transform:
#    - name: rotate
#      args: 
#        angle_deg: 30
    - name: aug
      args:
        apply_scale: true
        apply_rotation: true # y-axis random rotation

test_dataset: 
  name: modelnet
  args:
    root_dir: modelnet40_manually_aligned
    class_map: modelnet11
    split: test
  transform:
#    - name: rotate
#      args: 
#        angle_deg: 30
    - name: aug
      args:
        apply_scale: true
        apply_rotation: true # y-axis random rotation
  
encoder: 
  name: pointmae_encoder
  args: {}

head: 
  name: pointmae_decoder
  args: {}

loss: chamfer_distance_l2

optimizer:
  name: adamw
  args:
    lr: 0.001
    weight_decay: 0.05
scheduler:
  name: coslr
  args:
    epochs: 300
    initial_epochs: 10
    
epochs: 300
batch_size: 128
lr: 0.001
weight_decay: 0.005
ddp: true