dataset: 
  train:
    name: modelnet_render
    args:
      root: modelnet40_manually_aligned
      class_map: modelnet11
      split: train
      num_views: 3
      viewpoint_mode: fixed   # fixed, auto
    transform:
      - name: aug
        args:
          apply_scale: true
          apply_rotation: true

  val: 
    name: modelnet_render
    args:
      root: modelnet40_manually_aligned
      class_map: modelnet11
      split: test
      num_views: 3
      viewpoint_mode: fixed   # fixed, auto

  test: 
    name: scanobjectnn
    args:
      root: main_split_nobg
      class_map: scanobjectnn11
      split: test
      normalize: true

encoder: 
  name: pointmae_encoder
  args:
    mask_type: rand
    group_encoder: default
    noaug: false

head: 
  name: pointmae_decoder
  args: {}

loss: chamfer_distance_l2

optimizer:
  name: adamw
  args:
    lr: 0.001
    weight_decay: 0.05
    
scheduler:
  name: coslr
  args:
    initial_epochs: 10
    
epochs: 300
batch_size: 128
ddp: false
pretrain: true
